CADDY_VERSION=$(cat CADDY.version)
CADDY_DOCKER_VERSION=$(cat CADDY-DOCKER.version)
VERSION="${CADDY_VERSION}-2"

BUILDAH_ARGS="--build-arg CADDY_VERSION=${CADDY_VERSION} --build-arg CADDY_DOCKER_VERSION=${CADDY_DOCKER_VERSION} --build-arg VERSION=${VERSION}"
ARCHITECTURES="amd64"
