stages:
  - build

build:
  tags:
    - docker-build
  stage: build
  image: docker.io/enrico204/buildah-builder:1.27.0-1
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  before_script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - bash -x build_images.sh
  after_script:
    - buildah logout $CI_REGISTRY
