stages:
  - build

build:
  tags:
    - docker-build
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - bash build_images.sh
  after_script:
    - docker logout $CI_REGISTRY
