name: BuildImages
on:
  push:
    branches:
      - master

jobs:
  BuildImages:
    runs-on: host-linux-amd64
    container:
      volumes:
        - /var/lib/gitea-act-runner/.cache/:/var/lib/gitea-act-runner/.cache/
    steps:
      - name: Checking out the repository
        uses: https://git.netsplit.it/actions/git-clone@v1
        with:
          token: ${{ github.token }}
      - name: Login into registries
        run: |
          buildah login -u $NETSPLIT_REGISTRY_USER -p $NETSPLIT_REGISTRY_PASS registry-1.docker.io
          buildah login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS hub.docker.com
      - name: Build images
        run: podman run -it --rm --privileged -v "$(pwd):/src/" -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro --workdir /src/ hub.netsplit.it/utilities/buildah-builder:1.36.0-2 /bin/bash -x build_images.sh
      - name: Logout from the registry
        run: |
          buildah logout registry-1.docker.io
          buildah logout hub.netsplit.it
        if: always()
