name: BuildImages
on:
  push:
    branches:
      - master

jobs:
  BuildImages:
    runs-on: host-linux-amd64
    container:
      volumes:
        - /var/lib/gitea-act-runner/.cache/:/var/lib/gitea-act-runner/.cache/
    steps:
      - name: Checking out the repository
        uses: https://git.netsplit.it/actions/git-clone@v2
        with:
          token: ${{ github.token }}
      - name: Login into hub.netsplit.it
        run: buildah login -u ${{ secrets.NETSPLIT_REGISTRY_USER }} -p ${{ secrets.NETSPLIT_REGISTRY_PASS }} hub.netsplit.it
      - name: Login into Docker Hub
        run: buildah login -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_PASS }} registry-1.docker.io
      - name: Build images
        run: podman run -it --rm --privileged -v "$(pwd):/src/" -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro --workdir /src/ hub.netsplit.it/utilities/buildah-builder:1.36.0-2 /bin/bash -x build_images.sh
      - name: Logout from the registry
        run: buildah logout registry-1.docker.io
        if: always()
      - name: Logout from the registry
        run: buildah logout hub.netsplit.it
        if: always()
