name: BuildImages
on:
  push:
    branches:
      - master

jobs:
  BuildImages:
    runs-on: host-linux-amd64
    container:
      volumes:
        - /var/lib/gitea-act-runner/.cache/:/var/lib/gitea-act-runner/.cache/
    steps:
      - name: Checking out the repository
        uses: https://git.netsplit.it/actions/git-clone@v1
        with:
          token: ${{ github.token }}
      # TODO: login
      # - name: Login into the registry
      #   run: buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD hub.netsplit.it
      - name: Build images
        run: podman run -it --rm --privileged -v "$(pwd):/src/" -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro --workdir /src/ hub.netsplit.it/utilities/buildah-builder:1.36.0-2 /bin/bash -x build_images.sh
      # - name: Logout from the registry
      #   run: buildah logout hub.netsplit.it
      #   if: always()
