BUILDAH_ARGS=-f Dockerfile
VERSION=20240328

docker:
	buildah manifest rm containers-storage:${IMAGE_PATH}:${VERSION} > /dev/null 2>&1 || true
	buildah manifest create ${IMAGE_PATH}:${VERSION}

	buildah bud ${BUILDAH_ARGS} --manifest ${IMAGE_PATH}:${VERSION} --arch amd64
	buildah bud ${BUILDAH_ARGS} --manifest ${IMAGE_PATH}:${VERSION} --arch arm64 --variant v8

push:
	buildah manifest push --all --format=docker ${IMAGE_PATH}:${VERSION} docker://${IMAGE_PATH}:${VERSION}

version:
	@echo ${VERSION}

inspect:
	buildah manifest inspect ${IMAGE_PATH}:${VERSION}
