GO_VERSION=$(cat GO.version)
VSCODE_VERSION=$(cat VSCODE.version)
DEBIAN_CODENAME=bookworm
VERSION=${VSCODE_VERSION}-${DEBIAN_CODENAME}-go${GO_VERSION}-3

BUILDAH_ARGS="--build-arg GO_VERSION=${GO_VERSION} --build-arg DEBIAN_CODENAME=${DEBIAN_CODENAME} --build-arg VSCODE_VERSION=${VSCODE_VERSION}"