GO_VERSION=$(cat GO.version)
THEIA_VERSION=$(cat THEIA.version)
VERSION=${THEIA_VERSION}-go${GO_VERSION}-1

BUILDAH_ARGS="--build-arg GO_VERSION=${GO_VERSION} --build-arg THEIA_VERSION=${THEIA_VERSION}"