CERTBOT_VERSION=$(cat CERTBOT.version)
PLUGIN_VERSION=2.0.1
VERSION="${CERTBOT_VERSION}-${PLUGIN_VERSION}-1"

BUILDAH_ARGS="--build-arg CERTBOT_VERSION=${CERTBOT_VERSION} --build-arg PLUGIN_VERSION=${PLUGIN_VERSION} --build-arg VERSION=${VERSION}"
ARCHITECTURES="amd64"
