GO_VERSION=$(cat GO.version)
SUPERCRONIC_VERSION=$(cat SUPERCRONIC.version)
VERSION=${GO_VERSION}-${SUPERCRONIC_VERSION}-1

BUILDAH_ARGS="--build-arg SUPERCRONIC_VERSION=${SUPERCRONIC_VERSION} --build-arg GO_VERSION=${GO_VERSION}"