services:
  jupyterlab:
    image: enrico204/jupyter-lab:2024-04-01-1
    #build: .
#    ports:
#      - 127.0.0.1:8888:8888
    environment:
      GRANT_SUDO: yes
    network_mode: host
    volumes:
      - /home/enrico/git/:/home/jovyan/work/
      - /dataset/:/dataset/
    command:
      - jupyter-lab
      - --ip='*'
      - --NotebookApp.token=''
      - --NotebookApp.password=''
      - --ResourceUseDisplay.track_cpu_percent=True
      - --ResourceUseDisplay.enable_prometheus_metrics=False
